# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c70f869c65c2cdb60a433a93ac0ff0e5"
application_url = "https://app.connect-ecommerce.com/"
embedded = true
name = "Connect Ecommerce"
handle = "connect-ecommerce"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_inventory,read_customers,read_orders"

[auth]
redirect_urls = [ "https://app.connect-ecommerce.com/authenticate" ]
